# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 056d404eb0834e7b25ac636ae0bb85a50e723b1680efe509fd7015a45ff9eceed90c45e43292bcdb30643b9912b45f129f25ceb0151f9b72f21702323090b293

test:
  secret_key_base: 78e79ae67264cc5e32b384263ce16bb902f04b94ab2f32061e02183d528c6bf0f8ca2488fc468e63e0797d38e7a99fb156f03d795bfe0bffd6b6ad0f550558e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
